version: '3.8'

services:
  app:
    build: .
    container_name: movie_recommendation_app
    ports:
      - "5001:5001"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j_password # Change this to your Neo4j password
      - NEO4J_DATABASE=neo4j
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.3.3
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password # Change this to your Neo4j password